### ISSUE TITLE
运行dockerized-openoffice的容器中是否还运行着Ubuntu14.04?

### ISSUE THREAD

**Issue by Joeylulu** [tobegit3hub/dockerized-openoffice#3]
根据您的Dockerfile来看，生成的镜像中包括了Ubuntu14.04的环境，这个应用程序是跑在容器里的Ubuntu中 还是docker的HostOS上？因为我觉得如果在容器中跑应用程序还需要运行着“Guest OS”来提供环境，那用“轻量级”来描述容器 ，似乎没有意义。

**Comment by tobegit3hub** [comment]
这样的，docker只是做进程级别的隔离，所以都是用了host的内核，而Dockerfile指定的Ubuntu其实只包含了Ubuntu的软件环境（例如预装python和apt-get工具等）。容器“轻量级”的概念是相对虚拟机而言的，因为共享内核和操作系统，因此容器会比虚拟机体积小。

**Comment by Joeylulu** [comment]
奥.. 明白了 感谢您的回复~

**Comment by tobegit3hub** [comment]
You're welcome :smile:
